#!/usr/bin/env python3
"""OpenReview transfer helper (dry-run first).

This script prepares and optionally applies a transfer payload from a source note
(or JSON file) to a target venue invitation.

Modes:
- dry-run (default): emit payload JSON only
- apply: write to OpenReview when --apply is set and openreview is installed
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class TransferConfig:
    source_note_id: str | None
    source_json: str | None
    venue: str
    invitation: str
    title_field: str
    abstract_field: str
    authors_field: str
    authorids_field: str
    apply: bool
    out: str


def _load_source(cfg: TransferConfig) -> dict[str, Any]:
    if cfg.source_json:
        return json.loads(Path(cfg.source_json).read_text())

    if not cfg.source_note_id:
        raise ValueError("Provide either --source-json or --source-note-id")

    try:
        import openreview  # type: ignore
    except Exception as exc:
        raise RuntimeError(
            "openreview package is required for --source-note-id mode. "
            "Install with: pip install openreview-py"
        ) from exc

    client = _build_client(openreview)
    note = client.get_note(cfg.source_note_id)
    return {
        "id": getattr(note, "id", cfg.source_note_id),
        "content": dict(getattr(note, "content", {}) or {}),
        "authors": list(getattr(note, "authors", []) or []),
        "authorids": list(getattr(note, "authorids", []) or []),
        "title": (getattr(note, "content", {}) or {}).get("title", ""),
        "abstract": (getattr(note, "content", {}) or {}).get("abstract", ""),
    }


def _build_client(openreview_mod):
    baseurl = os.environ.get("OPENREVIEW_BASEURL", "https://api2.openreview.net")
    token = os.environ.get("OPENREVIEW_TOKEN")
    username = os.environ.get("OPENREVIEW_USERNAME")
    password = os.environ.get("OPENREVIEW_PASSWORD")

    if token:
        return openreview_mod.api.OpenReviewClient(baseurl=baseurl, token=token)
    if username and password:
        return openreview_mod.api.OpenReviewClient(baseurl=baseurl, username=username, password=password)
    raise RuntimeError(
        "Missing credentials. Set OPENREVIEW_TOKEN or OPENREVIEW_USERNAME+OPENREVIEW_PASSWORD"
    )


def _get_content_value(content: dict[str, Any], key: str, default: Any = "") -> Any:
    v = content.get(key, default)
    if isinstance(v, dict) and "value" in v:
        return v.get("value")
    return v


def _build_payload(cfg: TransferConfig, source: dict[str, Any]) -> dict[str, Any]:
    content = source.get("content", {}) or {}
    title = _get_content_value(content, "title", source.get("title", ""))
    abstract = _get_content_value(content, "abstract", source.get("abstract", ""))
    authors = _get_content_value(content, "authors", source.get("authors", []))
    authorids = _get_content_value(content, "authorids", source.get("authorids", []))

    payload = {
        "invitation": cfg.invitation,
        "venue": cfg.venue,
        "content": {
            cfg.title_field: {"value": title},
            cfg.abstract_field: {"value": abstract},
            cfg.authors_field: {"value": authors},
            cfg.authorids_field: {"value": authorids},
            "_source_note_id": {"value": source.get("id", "")},
            "_transfer_note": {
                "value": "Generated by browser-agent scripts/or_transfer.py (dry-run-first workflow)"
            },
        },
    }
    return payload


def _apply_payload(payload: dict[str, Any]) -> dict[str, Any]:
    try:
        import openreview  # type: ignore
    except Exception as exc:
        raise RuntimeError("Install openreview-py to use --apply") from exc

    client = _build_client(openreview)
    note = openreview.api.Note(invitation=payload["invitation"], content=payload["content"])
    created = client.post_note(note)
    return {"id": getattr(created, "id", None), "invitation": payload["invitation"]}


def parse_args() -> TransferConfig:
    ap = argparse.ArgumentParser(description="OpenReview transfer helper (dry-run-first)")
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--source-note-id", help="OpenReview source note id")
    src.add_argument("--source-json", help="Source note JSON path")
    ap.add_argument("--venue", required=True, help="Target venue id, for metadata")
    ap.add_argument("--invitation", required=True, help="Target invitation id")
    ap.add_argument("--title-field", default="title")
    ap.add_argument("--abstract-field", default="abstract")
    ap.add_argument("--authors-field", default="authors")
    ap.add_argument("--authorids-field", default="authorids")
    ap.add_argument("--apply", action="store_true", help="Apply to OpenReview (disabled by default)")
    ap.add_argument("--out", default="transfer_payload.json", help="Output payload JSON path")
    ns = ap.parse_args()
    return TransferConfig(
        source_note_id=ns.source_note_id,
        source_json=ns.source_json,
        venue=ns.venue,
        invitation=ns.invitation,
        title_field=ns.title_field,
        abstract_field=ns.abstract_field,
        authors_field=ns.authors_field,
        authorids_field=ns.authorids_field,
        apply=ns.apply,
        out=ns.out,
    )


def main() -> int:
    cfg = parse_args()
    source = _load_source(cfg)
    payload = _build_payload(cfg, source)
    Path(cfg.out).write_text(json.dumps(payload, ensure_ascii=False, indent=2))
    print(f"[dry-run] payload written: {cfg.out}")

    if not cfg.apply:
        print("[dry-run] no write performed (use --apply to post to OpenReview)")
        return 0

    created = _apply_payload(payload)
    print(json.dumps({"applied": True, "result": created}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
